from enum import Enum
from typing import List, TypedDict

class Area(str, Enum):
    vacation_island_resort = "Vacation Island Resort"
    vacation_beach = "Vacation Beach"
    vacation_forest = "Vacation Forest"
    vacation_mountain = "Vacation Mountain"
    dive_site = "Dive Site"
    hiking_trail = "Hiking Trail"
    overlook = "Overlook"

class LocationInfo(TypedDict):
    name: str
    id: int
    inGameId: str
    needsCamera: bool
    area: Area
    additionalAreas: List[Area]

base_id = 94202000

location_table: List[LocationInfo] = [
    {"name": "Vacation Beach - Block The Sun",
        "id": base_id + 1,
        "inGameId": "CoolDownSunTanBot",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - R e l a x",
        "id": base_id + 2,
        "inGameId": "DoYoga",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Good At Sports I",
        "id": base_id + 3,
        "inGameId": "BeatSportSet_Set1",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Good At Sports II",
        "id": base_id + 4,
        "inGameId": "BeatSportSet_Set2",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": [Area.vacation_forest, Area.vacation_island_resort]},
    {"name": "Vacation Beach - Beach Bugs",
        "id": base_id + 5,
        "inGameId": "FindBeachBugs",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sandcastles I",
        "id": base_id + 6,
        "inGameId": "CompleteAllSandCastles_Basic",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sandcastles II",
        "id": base_id + 7,
        "inGameId": "CompleteAllSandCastles_Beginner",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sandcastles III",
        "id": base_id + 8,
        "inGameId": "CompleteAllSandCastles_Intermediate",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sandcastles IV",
        "id": base_id + 9,
        "inGameId": "CompleteAllSandCastles_Advanced",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sandcastles V",
        "id": base_id + 10,
        "inGameId": "CompleteAllSandCastles_Master",
        "needsCamera": False,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Sweet Selfie",
        "id": base_id + 11,
        "inGameId": "HandInDiveBotSelfie",
        "needsCamera": True,
		"area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Dive Site - Sea Shanty",
        "id": base_id + 12,
        "inGameId": "DiveSite_PlaySeaShanty",
        "needsCamera": False,
		"area": Area.dive_site,
        "additionalAreas": []},
    {"name": "Dive Site - Open BotBeard's Treasure",
        "id": base_id + 13,
        "inGameId": "DiveSite_OpenTreasureChest",
        "needsCamera": False,
		"area": Area.dive_site,
        "additionalAreas": []},
    {"name": "Dive Site - Sea Life Snaps I",
        "id": base_id + 14,
        "inGameId": "DiveSite_SeaLifePhotography_Set1",
        "needsCamera": True,
		"area": Area.dive_site,
        "additionalAreas": []},
    {"name": "Dive Site - Sea Life Snaps II",
        "id": base_id + 15,
        "inGameId": "DiveSite_SeaLifePhotography_Set2",
        "needsCamera": True,
		"area": Area.dive_site,
        "additionalAreas": []},
    {"name": "Vacation Beach - Beach Orders I",
        "id": base_id + 16,
        "inGameId": "BeachFoodOrders_GetMemorySet1",
        "needsCamera": False,
        "area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Beach Orders II",
        "id": base_id + 17,
        "inGameId": "BeachFoodOrders_GetMemorySet2",
        "needsCamera": False,
        "area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Beach Orders III",
        "id": base_id + 18,
        "inGameId": "BeachFoodOrders_GetMemorySet3",
        "needsCamera": False,
        "area": Area.vacation_beach,
        "additionalAreas": [Area.vacation_forest]},
    {"name": "Vacation Beach - Beach Orders IV",
        "id": base_id + 19,
        "inGameId": "BeachFoodOrders_GetMemorySet4",
        "needsCamera": False,
        "area": Area.vacation_beach,
        "additionalAreas": [Area.hiking_trail, Area.vacation_forest, Area.dive_site, Area.vacation_mountain]},
    {"name": "Vacation Beach - Beach Photos I",
        "id": base_id + 20,
        "inGameId": "FinishPostcardCollection_Beach_1",
        "needsCamera": True,
        "area": Area.vacation_beach,
        "additionalAreas": []},
    {"name": "Vacation Beach - Beach Photos II",
        "id": base_id + 21,
        "inGameId": "FinishPostcardCollection_Beach_2",
        "needsCamera": True,
        "area": Area.vacation_beach,
        "additionalAreas": [Area.dive_site]},
    {"name": "Vacation Beach - Beach Photos III",
        "id": base_id + 22,
        "inGameId": "FinishPostcardCollection_Beach_3",
        "needsCamera": True,
        "area": Area.vacation_beach,
        "additionalAreas": [Area.dive_site, Area.vacation_forest, Area.vacation_island_resort, Area.vacation_mountain]},
    {"name": "Vacation Beach - Beach Photos IV",
        "id": base_id + 23,
        "inGameId": "FinishPostcardCollection_Beach_4",
        "needsCamera": True,
        "area": Area.vacation_beach,
        "additionalAreas": [Area.vacation_forest, Area.vacation_island_resort, Area.vacation_mountain]},

    {"name": "Vacation Forest - Fish Finder I",
        "id": base_id + 24,
        "inGameId": "RiverFishOrders_Set1",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Fish Finder II",
        "id": base_id + 25,
        "inGameId": "RiverFishOrders_Set2",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Fish Finder III",
        "id": base_id + 26,
        "inGameId": "RiverFishOrders_Set3",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_mountain, Area.dive_site]},
    {"name": "Vacation Forest - Painting I",
        "id": base_id + 27,
        "inGameId": "FinishPaintingsI",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Painting II",
        "id": base_id + 28,
        "inGameId": "FinishPaintingsII",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_beach, Area.vacation_mountain]},
    {"name": "Vacation Forest - Forest Bugs",
        "id": base_id + 29,
        "inGameId": "FindForestBugs",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Forest Targets",
        "id": base_id + 30,
        "inGameId": "ForestTargetsAll_SpeakToBot",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Beach Targets",
        "id": base_id + 31,
        "inGameId": "BeachTargetsAll_SpeakToBot",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_beach]},
    {"name": "Vacation Forest - Mountain Targets",
        "id": base_id + 32,
        "inGameId": "MountainTargetsAll_SpeakToBot",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_mountain, Area.overlook]},
    {"name": "Vacation Forest - Spooky Story",
        "id": base_id + 33,
        "inGameId": "ListenedToMultiPartCampfireStory",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Garden Variety",
        "id": base_id + 34,
        "inGameId": "CompletePlanting",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Forest Orders I",
        "id": base_id + 35,
        "inGameId": "ForestFoodOrders_GetMemorySet1",
        "needsCamera": False,
		"area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Forest Orders II",
        "id": base_id + 36,
        "inGameId": "ForestFoodOrders_GetMemorySet2",
        "needsCamera": False,
        "area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Forest Orders III",
        "id": base_id + 37,
        "inGameId": "ForestFoodOrders_GetMemorySet3",
        "needsCamera": False,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_island_resort, Area.hiking_trail, Area.dive_site, Area.vacation_mountain]},
    {"name": "Vacation Forest - Forest Orders IV",
        "id": base_id + 38,
        "inGameId": "ForestFoodOrders_GetMemorySet4",
        "needsCamera": False,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.hiking_trail, Area.vacation_mountain, Area.vacation_beach]},
    {"name": "Hiking Trail - Skipping ROCKS",
        "id": base_id + 39,
        "inGameId": "CompleteRockSkippingHighScore",
        "needsCamera": False,
        "area": Area.hiking_trail,
        "additionalAreas": []},
    {"name": "Hiking Trail - Bird Observer",
        "id": base_id + 40,
        "inGameId": "CompletedBirdWatching",
        "needsCamera": True,
        "area": Area.hiking_trail,
        "additionalAreas": []},
    {"name": "Hiking Trail - Hike Selfie",
        "id": base_id + 41,
        "inGameId": "TakePictureAtHikingPhotoBooth",
        "needsCamera": True,
        "area": Area.hiking_trail,
        "additionalAreas": []},
    {"name": "Hiking Trail - Turn On Geyser",
        "id": base_id + 42,
        "inGameId": "CompleteGeyser",
        "needsCamera": False,
        "area": Area.hiking_trail,
        "additionalAreas": []},
    {"name": "Vacation Forest - Raft Master",
        "id": base_id + 43,
        "inGameId": "FinishRaftingGame_AllLevels",
        "needsCamera": False,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.hiking_trail]},
    {"name": "Vacation Forest - Forest Photos I",
        "id": base_id + 44,
        "inGameId": "FinishPostcardCollection_Forest_1",
        "needsCamera": True,
        "area": Area.vacation_forest,
        "additionalAreas": []},
    {"name": "Vacation Forest - Forest Photos II",
        "id": base_id + 45,
        "inGameId": "FinishPostcardCollection_Forest_2",
        "needsCamera": True,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.hiking_trail]},
    {"name": "Vacation Forest - Forest Photos III",
        "id": base_id + 46,
        "inGameId": "FinishPostcardCollection_Forest_3",
        "needsCamera": True,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.hiking_trail, Area.vacation_beach, Area.vacation_mountain]},
    {"name": "Vacation Forest - Forest Photos IV",
        "id": base_id + 47,
        "inGameId": "FinishPostcardCollection_Forest_4",
        "needsCamera": True,
        "area": Area.vacation_forest,
        "additionalAreas": [Area.vacation_beach, Area.vacation_island_resort]},

    {"name": "Vacation Mountain - Warm Winter",
        "id": base_id + 48,
        "inGameId": "GiveWaterToWarmBot",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Knitted Gift",
        "id": base_id + 49,
        "inGameId": "DeliverKnitBotKnitGift",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Good Listener",
        "id": base_id + 50,
        "inGameId": "ListenToHotTubMonologue",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Orders I",
        "id": base_id + 51,
        "inGameId": "MountainFoodOrders_GetMemorySet1",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Orders II",
        "id": base_id + 52,
        "inGameId": "MountainFoodOrders_GetMemorySet2",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Orders III",
        "id": base_id + 53,
        "inGameId": "MountainFoodOrders_GetMemorySet3",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.overlook, Area.vacation_forest, Area.vacation_beach, Area.vacation_island_resort]},
    {"name": "Vacation Mountain - Mountain Orders IV",
        "id": base_id + 54,
        "inGameId": "MountainFoodOrders_GetMemorySet4",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.vacation_beach, Area.hiking_trail, Area.overlook, Area.vacation_forest]},
    {"name": "Vacation Mountain - Puzzle Master",
        "id": base_id + 55,
        "inGameId": "CompleteJigsawPuzzle",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Ice Sculptures I",
        "id": base_id + 56,
        "inGameId": "CompleteAllIceSculptures_101",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Ice Sculptures II",
        "id": base_id + 57,
        "inGameId": "CompleteAllIceSculptures_Beginner",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Ice Sculptures III",
        "id": base_id + 58,
        "inGameId": "CompleteAllIceSculptures_Intermediate",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Ice Sculptures IV",
        "id": base_id + 59,
        "inGameId": "CompleteAllIceSculptures_Advanced",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Ice Sculptures V",
        "id": base_id + 60,
        "inGameId": "CompleteAllIceSculptures_Master",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Snow Safety Lesson",
        "id": base_id + 61,
        "inGameId": "SnowThrowingCompleteAllSigns",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Bugs",
        "id": base_id + 62,
        "inGameId": "FindMountainBugs",
        "needsCamera": False,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Photobombinable",
        "id": base_id + 63,
        "inGameId": "TurnInPhotobombinableSnowBotPhoto",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.overlook, Area.vacation_island_resort]},
    {"name": "Overlook - On Hill Skiing I",
        "id": base_id + 64,
        "inGameId": "FinishSkiing1",
        "needsCamera": False,
        "area": Area.overlook,
        "additionalAreas": []},
    {"name": "Overlook - On Hill Skiing II",
        "id": base_id + 65,
        "inGameId": "FinishSkiing2",
        "needsCamera": False,
        "area": Area.overlook,
        "additionalAreas": []},
    {"name": "Overlook - Mountain Climbing I",
        "id": base_id + 66,
        "inGameId": "FinishClimbingGame1",
        "needsCamera": False,
        "area": Area.overlook,
        "additionalAreas": []},
    {"name": "Overlook - Mountain Climbing II",
        "id": base_id + 67,
        "inGameId": "FinishClimbingGame2",
        "needsCamera": False,
        "area": Area.overlook,
        "additionalAreas": []},
    {"name": "Overlook - Raise Flag At Summit",
        "id": base_id + 68,
        "inGameId": "CompleteSummit",
        "needsCamera": False,
        "area": Area.overlook,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Photos I",
        "id": base_id + 69,
        "inGameId": "FinishPostcardCollection_Mountain_1",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": []},
    {"name": "Vacation Mountain - Mountain Photos II",
        "id": base_id + 70,
        "inGameId": "FinishPostcardCollection_Mountain_2",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.overlook]},
    {"name": "Vacation Mountain - Mountain Photos III",
        "id": base_id + 71,
        "inGameId": "FinishPostcardCollection_Mountain_3",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.overlook, Area.vacation_beach, Area.vacation_forest]},
    {"name": "Vacation Mountain - Mountain Photos IV",
        "id": base_id + 72,
        "inGameId": "FinishPostcardCollection_Mountain_4",
        "needsCamera": True,
        "area": Area.vacation_mountain,
        "additionalAreas": [Area.dive_site, Area.vacation_forest, Area.vacation_island_resort]},
]
